import { Brain, Palette, Cog, Search, FlaskConical } from 'lucide-react';
import type { AgentConfig, AgentId, AgentStatus, StatusStyle, PipelineScenario, FeedbackEntry } from './types';

export const AGENTS: AgentConfig[] = [
  { id: 'planner', name: 'Planner', icon: Brain, role: 'Orchestrateur', color: 'var(--color-agent-planner)' },
  { id: 'designer', name: 'Designer', icon: Palette, role: 'UI / Frontend', color: 'var(--color-agent-designer)' },
  { id: 'backend', name: 'Backend', icon: Cog, role: 'API / DB', color: 'var(--color-agent-backend)' },
  { id: 'reviewer', name: 'Reviewer', icon: Search, role: 'Code Review', color: 'var(--color-agent-reviewer)' },
  { id: 'tester', name: 'Tester', icon: FlaskConical, role: 'Tests & QA', color: 'var(--color-agent-tester)' },
];

export const STATUS_CONFIG: Record<AgentStatus, StatusStyle> = {
  idle: {
    label: 'En attente',
    bgClass: 'bg-muted',
    borderClass: 'border-border',
    dotClass: 'bg-status-idle',
    pulse: false,
    labelColor: 'var(--color-status-idle)',
  },
  running: {
    label: 'En cours',
    bgClass: 'bg-amber-950/20 dark:bg-amber-950/30',
    borderClass: 'border-amber-500',
    dotClass: 'bg-status-running',
    pulse: true,
    labelColor: 'var(--color-status-running)',
  },
  completed: {
    label: 'Termine',
    bgClass: 'bg-emerald-950/20 dark:bg-emerald-950/30',
    borderClass: 'border-emerald-500',
    dotClass: 'bg-status-completed',
    pulse: false,
    labelColor: 'var(--color-status-completed)',
  },
  error: {
    label: 'Erreur',
    bgClass: 'bg-red-950/30 dark:bg-red-950/40',
    borderClass: 'border-red-500',
    dotClass: 'bg-status-error',
    pulse: true,
    labelColor: 'var(--color-status-error)',
  },
  paused: {
    label: 'En pause',
    bgClass: 'bg-amber-950/20 dark:bg-amber-950/30',
    borderClass: 'border-amber-500',
    dotClass: 'bg-status-paused',
    pulse: true,
    labelColor: 'var(--color-status-paused)',
  },
  blocked: {
    label: 'Bloque',
    bgClass: 'bg-fuchsia-950/20 dark:bg-fuchsia-950/30',
    borderClass: 'border-fuchsia-500',
    dotClass: 'bg-status-blocked',
    pulse: false,
    labelColor: 'var(--color-status-blocked)',
  },
};

export const PHASES = [
  { num: 1, label: 'Planification' },
  { num: 2, label: 'Execution' },
  { num: 3, label: 'Revue' },
  { num: 4, label: 'Tests' },
] as const;

const ZERO_SCORES: Record<AgentId, number> = { planner: 0, designer: 0, backend: 0, reviewer: 0, tester: 0 };

const SAMPLE_FEEDBACK: FeedbackEntry = {
  id: 1,
  time: '10:01:37',
  from: 'reviewer',
  target: ['backend'],
  action: 'redispatch',
  severity: 'blocking',
  message: 'Coordonnees station Bondy manquantes, travelTimeToNext absent entre Gargan et Les Pavillons',
  iteration: 0,
};

export const DEMO_SCENARIOS: PipelineScenario[] = [
  {
    name: 'Pipeline au repos',
    state: { planner: 'idle', designer: 'idle', backend: 'idle', reviewer: 'idle', tester: 'idle' },
    phase: 0,
    iterations: 0,
    maxIterations: 3,
    status: 'idle',
    request: 'En attente d\'une demande...',
    logs: [],
    scores: { ...ZERO_SCORES },
    autoApprove: true,
    startedAt: null,
    feedback: [],
    outputs: {},
    pendingPlan: null,
  },
  {
    name: 'Phase planification',
    state: { planner: 'running', designer: 'idle', backend: 'idle', reviewer: 'idle', tester: 'idle' },
    phase: 1,
    iterations: 0,
    maxIterations: 3,
    status: 'planning',
    request: 'Ajouter la ligne de tramway T4 avec ses 10 stations',
    logs: [
      { time: '10:00:01', agent: 'planner', msg: 'Analyse de la demande recue' },
      { time: '10:00:03', agent: 'planner', msg: 'Decomposition en 4 sous-taches identifiees' },
      { time: '10:00:04', agent: 'planner', msg: 'Dependances : designer || backend -> reviewer -> tester' },
    ],
    scores: { ...ZERO_SCORES },
    autoApprove: true,
    startedAt: null,
    feedback: [],
    outputs: {},
    pendingPlan: null,
  },
  {
    name: 'Execution parallele',
    state: { planner: 'completed', designer: 'running', backend: 'running', reviewer: 'idle', tester: 'idle' },
    phase: 2,
    iterations: 0,
    maxIterations: 3,
    status: 'executing',
    request: 'Ajouter la ligne de tramway T4 avec ses 10 stations',
    logs: [
      { time: '10:00:01', agent: 'planner', msg: 'Plan valide — lancement de l\'execution' },
      { time: '10:00:05', agent: 'designer', msg: 'Ajout du badge T4 dans LineBadge.tsx' },
      { time: '10:00:05', agent: 'backend', msg: 'Ajout des donnees T4 dans paris-transport.ts' },
      { time: '10:00:12', agent: 'designer', msg: 'Mise a jour de la page /lignes avec la nouvelle ligne' },
      { time: '10:00:14', agent: 'backend', msg: 'Creation de la migration Prisma pour les 10 stations' },
    ],
    scores: { ...ZERO_SCORES, planner: 85 },
    autoApprove: true,
    startedAt: null,
    feedback: [],
    outputs: {},
    pendingPlan: null,
  },
  {
    name: 'Revue — Probleme detecte',
    state: { planner: 'completed', designer: 'completed', backend: 'completed', reviewer: 'running', tester: 'paused' },
    phase: 3,
    iterations: 1,
    maxIterations: 3,
    status: 'reviewing',
    request: 'Ajouter la ligne de tramway T4 avec ses 10 stations',
    logs: [
      { time: '10:01:30', agent: 'reviewer', msg: 'Analyse de 6 fichiers modifies...' },
      { time: '10:01:35', agent: 'reviewer', msg: '[FEEDBACK → backend] BLOCKING: Coordonnees station Bondy manquantes' },
      { time: '10:01:36', agent: 'reviewer', msg: '[REDISPATCH] Iteration 1/3 — re-running: backend' },
      { time: '10:01:38', agent: 'planner', msg: 'Feedback recu — relance backend avec corrections' },
    ],
    scores: { ...ZERO_SCORES, planner: 85, designer: 78, backend: 35 },
    autoApprove: true,
    startedAt: null,
    feedback: [SAMPLE_FEEDBACK],
    outputs: {},
    pendingPlan: null,
  },
  {
    name: 'Tests en cours',
    state: { planner: 'completed', designer: 'completed', backend: 'completed', reviewer: 'completed', tester: 'running' },
    phase: 4,
    iterations: 1,
    maxIterations: 3,
    status: 'testing',
    request: 'Ajouter la ligne de tramway T4 avec ses 10 stations',
    logs: [
      { time: '10:03:00', agent: 'tester', msg: 'Execution de 8 tests unitaires...' },
      { time: '10:03:05', agent: 'tester', msg: 'graph.test.ts — 3/3 passes (T4 dans le graphe)' },
      { time: '10:03:08', agent: 'tester', msg: 'lines-api.test.ts — 2/2 passes (GET /api/lines)' },
      { time: '10:03:10', agent: 'tester', msg: 'pathfinder.test.ts — en cours...' },
    ],
    scores: { ...ZERO_SCORES, planner: 85, designer: 78, backend: 72, reviewer: 60 },
    autoApprove: true,
    startedAt: null,
    feedback: [SAMPLE_FEEDBACK],
    outputs: {},
    pendingPlan: null,
  },
  {
    name: 'Pipeline termine',
    state: { planner: 'completed', designer: 'completed', backend: 'completed', reviewer: 'completed', tester: 'completed' },
    phase: 4,
    iterations: 1,
    maxIterations: 3,
    status: 'completed',
    request: 'Ajouter la ligne de tramway T4 avec ses 10 stations',
    logs: [
      { time: '10:03:15', agent: 'tester', msg: 'Tous les tests passes — 8/8' },
      { time: '10:03:16', agent: 'tester', msg: 'Couverture : 87% statements, 82% branches' },
      { time: '10:03:17', agent: 'planner', msg: 'Pipeline termine avec succes (1 iteration de feedback)' },
    ],
    scores: { planner: 85, designer: 78, backend: 72, reviewer: 60, tester: 92 },
    autoApprove: true,
    startedAt: null,
    feedback: [SAMPLE_FEEDBACK],
    outputs: {},
    pendingPlan: null,
  },
];
